In [1]:
import pandas as pd
import numpy as np

In [6]:
ccode_iso = pd.read_excel("D:/kerja/asisten riset/vol/milkunC/achaidir/LUH2 2022/ISO-3166-Country-Code_Final.xlsx")
area_harvested = pd.read_csv("D:/kerja/asisten riset/vol/milkunC/achaidir/FAO/faostat_area_harvested.csv")
yield_absolute = pd.read_csv("D:/kerja/asisten riset/vol/milkunC/achaidir/FAO/faostat_yield_absolute.csv")

In [7]:
ccode_iso.head()

,ISO Country,alpha-2,alpha-3,country-code,iso_3166-2,Sub Region,ISO Region,IMAGE Region Code,IMAGE Region Name
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia
1,Albania,AL,ALB,8,ISO 3166-2:AL,Europe and Russia,Europe,CEU,C. Europe
2,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Middle East,Africa,NAF,N. Africa
3,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Oceania,OCE,Oceania
4,Andorra,AD,AND,20,ISO 3166-2:AD,Europe and Russia,Europe,WEU,W. Europe

### area harvested

In [8]:
area_harvested.head()

          Area  Year              IMAGE Classification     Value
0  Afghanistan  1970               Vegetables & fruits  211960.0
1  Afghanistan  1970  Other non-food & luxury & spices       0.0
2  Afghanistan  1970           Other temperate cereals  316800.0
3  Afghanistan  1970               Temperate oil crops   55960.0
4  Afghanistan  1970                             Maize  464400.0

In [10]:
area_harvested_merge = pd.merge(left=area_harvested, right=ccode_iso, left_on="Area", right_on="ISO Country")
area_harvested_merge.head()

,Area,Year,IMAGE Classification,Value,ISO Country,alpha-2,alpha-3,country-code,iso_3166-2,Sub Region,ISO Region,IMAGE Region Code,IMAGE Region Name
0,Afghanistan,1970,Vegetables & fruits,211960.0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia
1,Afghanistan,1970,Other non-food & luxury & spices,0.0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia
2,Afghanistan,1970,Other temperate cereals,316800.0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia
3,Afghanistan,1970,Temperate oil crops,55960.0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia
4,Afghanistan,1970,Maize,464400.0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia

In [12]:
area_harvested_merge_columns = area_harvested_merge[['ISO Country', 'alpha-2', 'alpha-3', 'country-code', 'iso_3166-2', 'Sub Region',
       'ISO Region', 'IMAGE Region Code', 'IMAGE Region Name','Year', 'IMAGE Classification', 'Value']]
area_harvested_merge_columns.head()

,ISO Country,alpha-2,alpha-3,country-code,iso_3166-2,Sub Region,ISO Region,IMAGE Region Code,IMAGE Region Name,Year,IMAGE Classification,Value
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia,1970,Vegetables & fruits,211960.0
1,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia,1970,Other non-food & luxury & spices,0.0
2,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia,1970,Other temperate cereals,316800.0
3,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia,1970,Temperate oil crops,55960.0
4,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia,1970,Maize,464400.0

### yield absolute

In [13]:
yield_absolute.head()

          Area  Year              IMAGE Classification        Value
0  Afghanistan  1970               Vegetables & fruits  12980818.72
1  Afghanistan  1970  Other non-food & luxury & spices         0.00
2  Afghanistan  1970           Other temperate cereals   3602026.80
3  Afghanistan  1970               Temperate oil crops    341002.56
4  Afghanistan  1970                             Maize   7229993.00

In [14]:
yield_absolute_merge = pd.merge(left=yield_absolute, right=ccode_iso, left_on="Area", right_on="ISO Country")
yield_absolute_merge.head()

,Area,Year,IMAGE Classification,Value,ISO Country,alpha-2,alpha-3,country-code,iso_3166-2,Sub Region,ISO Region,IMAGE Region Code,IMAGE Region Name
0,Afghanistan,1970,Vegetables & fruits,12980818.72,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia
1,Afghanistan,1970,Other non-food & luxury & spices,0.00,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia
2,Afghanistan,1970,Other temperate cereals,3602026.80,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia
3,Afghanistan,1970,Temperate oil crops,341002.56,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia
4,Afghanistan,1970,Maize,7229993.00,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia

In [15]:
yield_absolute_merge_columns = yield_absolute_merge[['ISO Country', 'alpha-2', 'alpha-3', 'country-code', 'iso_3166-2', 'Sub Region',
       'ISO Region', 'IMAGE Region Code', 'IMAGE Region Name','Year', 'IMAGE Classification', 'Value']]
yield_absolute_merge_columns.head()

,ISO Country,alpha-2,alpha-3,country-code,iso_3166-2,Sub Region,ISO Region,IMAGE Region Code,IMAGE Region Name,Year,IMAGE Classification,Value
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia,1970,Vegetables & fruits,12980818.72
1,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia,1970,Other non-food & luxury & spices,0.00
2,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia,1970,Other temperate cereals,3602026.80
3,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia,1970,Temperate oil crops,341002.56
4,Afghanistan,AF,AFG,4,ISO 3166-2:AF,South Asia,Asia,RSAS,Rest S. Asia,1970,Maize,7229993.00

In [16]:
area_harvested_merge_columns.to_excel("D:/kerja/asisten riset/vol/milkunC/achaidir/FAO/faostat_area_harvested_IMAGE.xlsx", index=False)
yield_absolute_merge_columns.to_excel("D:/kerja/asisten riset/vol/milkunC/achaidir/FAO/faostat_yield_absolute_IMAGE.xlsx", index=False)