In [7]:
import pandas as pd
import numpy as np
import xarray

In [ ]:
df_Physical = pd.read_excel("D:/kerja/asisten riset/code v/step 3/GbGlct/dataset/Physical to Harvested Area GFRAC.xlsx")
country_code = pd.read_excel("D:/kerja/asisten riset/vol/milkunC/achaidir/LUH2 2022/ISO-3166-Country-Code_Final.xlsx")
luh_static = xarray.open_dataset("D:/kerja/asisten riset/vol/milkunC/achaidir/LUH2 2022/CCODE_RASTER.nc", engine="netcdf4")
GFRAC = xarray.open_dataset("D:/kerja/asisten riset/vol/milkunC/achaidir/IMAGE PBL/SSP2/GFRAC_NEW.NC", engine="netcdf4")

In [90]:
df1_copy = df_Physical.copy()
df1_copy = df1_copy.rename(columns={"t" : "time"})

df1_copy = df1_copy[~df1_copy['NFBFC'].str.contains("biofuel")]
df1_copy.loc[:, 'RF/IR'] = np.where(np.arange(4192) % 32 < 16, "RF", "IR")
df1_copy['NFBFC'] = df1_copy['NFBFC'].apply(lambda x: x.replace('and', '&').replace('Plant-based fibers', 'Plant based fibres').replace('Oil, palm fruit', 'Oil & palm fruit').replace('Other non-food, luxury, spices', 'Other non-food & luxury & spices').replace('Vegetables or fruits', 'Vegetables & fruits').replace('Sugar Crops', 'Sugar crops'))
df1_copy["NGFBFC"] = df1_copy['RF/IR'] + " " + df1_copy['NFBFC']
df1_copy = df1_copy.drop(columns=["NFBFC", "RF/IR"])

years = list(range(1970, 2021, 5))

# Filter the DataFrame
df1_copy_filtered = df1_copy[df1_copy['time'].isin(years)]


columns = df1_copy.columns[1:-1].to_list()
df_pivot = df1_copy_filtered.pivot_table(columns=['NGFBFC','time'], values=columns, aggfunc="sum")
df_index = df_pivot.stack(level=0, future_stack=True).reset_index()
df_kofisien = df_index.rename(columns={"level_0" : "IMAGE Region Name"})
df_kofisien

time,IMAGE Region Name,NGFBFC,1970,1975,1980,1985,1990,1995,2000,2005,2010,2015,2020
0,Brazil,IR Maize,1.063706,1.062657,0.919990,0.881177,0.992373,1.007059,0.972441,1.095177,1.136088,1.268265,1.335402
1,Brazil,IR Oil & palm fruit,0.994118,0.993137,0.859804,0.823529,0.927451,0.941176,0.908824,1.023529,1.061765,1.185294,1.248039
2,Brazil,IR Other non-food & luxury & spices,0.994118,0.993137,0.859804,0.823529,0.927451,0.941176,0.908824,1.023529,1.061765,1.185294,1.248039
3,Brazil,IR Other temperate cereals,0.994118,0.993137,0.859804,0.823529,0.927451,0.941176,0.908824,1.023529,1.061765,1.185294,1.248039
4,Brazil,IR Plant based fibres,0.994118,0.993137,0.859804,0.823529,0.927451,0.941176,0.908824,1.023529,1.061765,1.185294,1.248039
...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,W. Europe,RF Tropical cereals,0.703922,0.715686,0.719608,0.728431,0.724510,0.696078,0.714706,0.703922,0.699020,0.698039,0.691176
860,W. Europe,RF Tropical oil crops,0.725039,0.737157,0.741196,0.750284,0.746245,0.716961,0.736147,0.725039,0.719990,0.718980,0.711912
861,W. Europe,RF Tropical roots & tubers,0.703922,0.715686,0.719608,0.728431,0.724510,0.696078,0.714706,0.703922,0.699020,0.698039,0.691176
862,W. Europe,RF Vegetables & fruits,0.703922,0.715686,0.719608,0.728431,0.724510,0.696078,0.714706,0.703922,0.699020,0.698039,0.691176
863,W. Europe,RF Wheat,0.732078,0.744314,0.748392,0.757569,0.753490,0.723921,0.743294,0.732078,0.726980,0.725961,0.718823

## eksperimen

In [6]:
df_rfWheat = pd.read_csv("D:/kerja/asisten riset/code v/review/dataset/rfWheat_df.csv")
df_rfWheat

,country,longitude,latitude,type,1970,1975,1980,1985,1990,1995,2000,2005,2010,2015,2020
0,Afghanistan,60.541666,33.041667,RF Wheat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,60.541666,33.125000,RF Wheat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,60.541666,33.208334,RF Wheat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,60.541666,33.541667,RF Wheat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,60.541666,33.625000,RF Wheat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2215719,Ã…land Islands,20.291666,60.125000,RF Wheat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2215720,Ã…land Islands,20.291666,60.208333,RF Wheat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2215721,Ã…land Islands,20.291666,60.291667,RF Wheat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2215722,Ã…land Islands,20.374999,60.041667,RF Wheat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2215723,Ã…land Islands,20.458333,60.041667,RF Wheat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_merge = pd.merge(left=df_rfWheat, right=country_code, left_on=['country'], right_on=['ISO Country'])
df_merge = df_merge.drop(columns=['country', 'ISO Country', 'alpha-2', 'alpha-3', 'country-code', 'iso_3166-2',
       'Sub Region', 'ISO Region', 'IMAGE Region Code'])
df_merge

,country,longitude,latitude,type,1970,1975,1980,1985,1990,1995,2000,2005,2010,2015,2020,IMAGE Region Name
0,Afghanistan,60.541666,33.041667,RF Wheat,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rest S. Asia
1,Afghanistan,60.541666,33.125000,RF Wheat,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rest S. Asia
2,Afghanistan,60.541666,33.208334,RF Wheat,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rest S. Asia
3,Afghanistan,60.541666,33.541667,RF Wheat,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rest S. Asia
4,Afghanistan,60.541666,33.625000,RF Wheat,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rest S. Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2208192,Zimbabwe,32.958332,-17.125000,RF Wheat,1.073856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rest S. Africa
2208193,Zimbabwe,32.958332,-17.041666,RF Wheat,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rest S. Africa
2208194,Zimbabwe,32.958332,-16.958333,RF Wheat,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rest S. Africa
2208195,Zimbabwe,32.958332,-16.875000,RF Wheat,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rest S. Africa
2208196,Zimbabwe,32.958332,-16.791666,RF Wheat,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rest S. Africa

In [138]:
df_merge.iloc[2208192, 4]

1.0738564

In [142]:
np.where(df_merge[(df_merge['type'] == 'RF Wheat') & (df_merge['IMAGE Region Name'] == 'Rest S. Africa')]['1970'].values == 1.0738564)

(array([68663], dtype=int64),)

In [116]:
df_kofisien[(df_kofisien['NGFBFC'] == 'RF Wheat') & (df_kofisien['IMAGE Region Name'] == 'Rest S. Africa')][1970]

543    0.722772
Name: 1970, dtype: float64

In [119]:
ex_data = np.multiply(df_merge[(df_merge['type'] == 'RF Wheat') & (df_merge['IMAGE Region Name'] == 'Rest S. Africa')]['1970'].to_numpy(),
                                                df_kofisien[(df_kofisien['NGFBFC'] == 'RF Wheat') & (df_kofisien['IMAGE Region Name'] == 'Rest S. Africa')][1970].to_numpy())

In [143]:
ex_data[68663]

0.776153660359072

### uji langsung

In [ ]:
area_harvested_zeros = np.zeros((11, 32, 2160, 4320), dtype='float32')

In [ ]:
gfrac_ngfbfc = df_kofisien['NGFBFC'].unique()
image_region = df_kofisien['IMAGE Region Name'].unique()

In [ ]:
import os
path_list = os.path.dirname #32

for file in path_list:
    df_path = pd.read_csv(f"D:/kerja/asisten riset/code v/review/dataset/{file}")

    df_merge = pd.merge(left=df_path, right=country_code, left_on=['country'], right_on=['ISO Country'])
    df_merge = df_merge.drop(columns=['country', 'ISO Country', 'alpha-2', 'alpha-3', 'country-code', 'iso_3166-2', 'Sub Region', 'ISO Region', 'IMAGE Region Code'])

    df_copy = df_merge.copy()

    for x, time in enumerate(range(1970, 2021, 5)):
        # for y, ngfbfc in enumerate(gfrac_ngfbfc):
            for region in image_region:
                df_copy[(df_copy['time'] == time) & (df_copy['type'] == ngfbfc) & (df_copy['IMAGE Region Name'] == region)][f'{time}'] = np.multiply(df_merge[(df_merge['time'] == time) & (df_merge['type'] == ngfbfc) & (df_merge['IMAGE Region Name'] == region)][f'{time}'],
                                            df_kofisien[(df_kofisien['time'] == time) & (df_kofisien['NGFBFC'] == ngfbfc) & (df_kofisien['IMAGE Region Name'] == region)][time])
                
    df_copy.to_csv()

In [ ]:
df_copy

In [ ]:
ccode_iso = list(country_code['country-code'])
cname_iso = list(country_code['ISO Country'])
cregion_iso = list(country_code['IMAGE Region Name'])


ccode_dict = {}
for i, ccode in enumerate(ccode_iso):
    ccode_dict[ccode] = cname_iso[i]

ccode_worldwide_int = luh_static['ccode'].to_numpy().astype('int64')

ccode_convert = np.zeros((2160, 4320), dtype="<U64") #rubah ke <U64
ccode_convert_cregion = np.zeros((2160, 4320), dtype="<U40") #rubah ke <U64

for i in range(2160):
    for j in range(4320):
        if (ccode_worldwide_int[i][j] in ccode_dict.keys()):
            ccode_convert[i][j] = ccode_dict[ccode_worldwide_int[i][j]]
        else:
            ccode_convert[i][j] = "ocean"

country = xarray.Dataset({"country": (["latitude", "longitude"], ccode_convert)},
                         coords={ "longitude": luh_static.coords["longitude"].to_numpy(), "latitude": luh_static.coords["latitude"].to_numpy()})

In [ ]:
# Buat kembali dataset xarray dari fubc_netcdf jika dibutuhkan
gfrac_areaharvested_netcdf = xarray.Dataset({
    "GFRAC_AH":(["time", "NGFBFC", "latitude", "longitude"], area_harvested_zeros)
    },coords={
        "time": pd.date_range(start='1970-01-01', end='2020-01-01', freq='5YS'),
        "NGFBFC" : gfrac_ngfbfc,
        "latitude": luh_static.coords["latitude"].to_numpy(),
        "longitude": luh_static.coords["longitude"].to_numpy()
})
gfrac_areaharvested_netcdf

In [ ]:
gfrac_ngfbfc_ir_rf = []
gfrac_ngfbfc_rf = []
gfrac_ngfbfc_ir = []

for idx, gfrac_cls in enumerate(gfrac_ngfbfc):
    if gfrac_cls[0:2] == b'RF':
        gfrac_ngfbfc_rf.append(gfrac_cls)
        gfrac_ngfbfc_ir_rf.append(gfrac_cls[3:])
    elif gfrac_cls[0:2] == b'IR':
        gfrac_ngfbfc_ir.append(gfrac_cls)
        gfrac_ngfbfc_ir_rf.append(gfrac_cls[3:])

gfrac_ngfbfc_ir_rf_list = gfrac_ngfbfc_ir_rf[:16]

gfrac5mins_new = np.zeros((11, 16, 2160, 4320), dtype="float32") #30 mins an

for i in range(11):
    gfrac5mins_new[i][0] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=0) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=16))
    gfrac5mins_new[i][1] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=1) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=17))
    gfrac5mins_new[i][2] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=2) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=18))
    gfrac5mins_new[i][3] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=3) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=19))
    gfrac5mins_new[i][4] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=4) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=20))
    gfrac5mins_new[i][5] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=5) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=21))
    gfrac5mins_new[i][6] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=6) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=22))
    gfrac5mins_new[i][7] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=7) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=23))
    gfrac5mins_new[i][8] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=8) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=24))
    gfrac5mins_new[i][9] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=9) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=25))
    gfrac5mins_new[i][10] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=10) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=26))
    gfrac5mins_new[i][11] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=11) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=27))
    gfrac5mins_new[i][12] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=12) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=28))
    gfrac5mins_new[i][13] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=13) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=29))
    gfrac5mins_new[i][14] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=14) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=30))
    gfrac5mins_new[i][15] = (gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=15) + gfrac_areaharvested_netcdf["GFRAC_AH"].isel(time=i, NGFBFC=31))

In [ ]:
gfrac5mins_new_netcdf = xarray.Dataset({
        "GFRAC_combined":(["time", "NGFBFC", "latitude", "longitude"], gfrac5mins_new)
    },coords={
        "time": pd.date_range(start='1970-01-01', end='2020-01-01', freq='5YS'),
        "NGFBFC": gfrac_ngfbfc,
        "latitude": luh_static.coords["latitude"].to_numpy(),
        "longitude": luh_static.coords["longitude"].to_numpy(),
    })

gfrac5mins_new_netcdf.to_netcdf("", mode="w", format="NETCDF4")